age: 1500
favorite_colors:
  - blue
  - green
city_time:
  - Warsaw
  - 35
children:
  - - John
    - 16
  - - Alan
    - 15
pictures_folder: ./images
picture_name: beautiful.jpg
two_values:
  value_2: second value
  value_1: first_value
