name: Publish

on:
  release:
    types: [released]

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Poetry
      run: |
        python -m pip install poetry==1.1.11
        poetry config virtualenvs.create false
    - name: Build and publish
      run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
